language: python
python:
  - "2.7"
  - "3.4"
  - "3.7"
  - "pypy"
  - "pypy3"

branches:
  only:
  - master

# we only need pytest to run this
install:
  - pip install pytest pylint

# command to run tests
script:
  - python setup.py install
  - pytest
  - pylint -dR -dC -dfixme src/fsource
